version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "8001:8001"
    environment:
      - ENV=production
      - DATABASE_URL=mysql+pymysql://root:password@db:3306/hr_recruitment
      - SECRET_KEY=${SECRET_KEY:-hr_recruitment_secret_key}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - MOCK_SERVICES=${MOCK_SERVICES:-True}
    depends_on:
      - db
    volumes:
      - ./backend:/app
    restart: always

  frontend:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    restart: always

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=hr_recruitment
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data:
