app = "hr-recruitment-system"

[build]
  dockerfile = "Dockerfile"

[env]
  ENV = "production"

[http_service]
  internal_port = 8001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
