---
name: 后端测试

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'
  pull_request:
    branches: [main]
    paths:
      - 'backend/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 设置Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: 安装依赖
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: 运行测试
        working-directory: ./backend
        env:
          ENV: test
          MOCK_SERVICES: "True"
        run: |
          pytest tests/ -v
